<?xml version="1.0"?>

<robot name="diff_robot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find rl_robot_description_pkg)/urdf/diff_robot_macro.xacro" /> 

	<!--Actual body/chassis of the robot-->
	<link name="base_link">
		<inertial>
			<mass value="${base_mass}" />
			<origin xyz="0 0 0" />
			<cylinder_inertia  m="${base_mass}" r="${base_radius}" h="${base_height}" />
		</inertial>    
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<cylinder length="${base_height}" radius="${base_radius}" />
			</geometry>
			<material name="White" />
		</visual>  
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0 " />
			<geometry>
				<cylinder length="${base_height}" radius="${base_radius}" />
			</geometry>
		</collision>     
	</link>

	<xacro:caster_joint 
		name="caster_front_link"
		parent="base_link"
		child="caster_front_link">
		<origin xyz="0.115 0.0 0.007" rpy="${-M_PI/2} 0 0"/>
	</xacro:caster_joint>

	<xacro:caster_link
		name="caster_front_link">
			<origin xyz="0 0.02 0" rpy="${M_PI/2} 0 0" />
	</xacro:caster_link>
	
	<xacro:caster_joint 
		name="caster_back_joint"
		parent="base_link"
		child="caster_back_link">
		<origin xyz="-0.135 0.0 0.009" rpy="${-M_PI/2} 0 0"/>
	</xacro:caster_joint>

	<xacro:caster_link
		name="caster_back_link">
			<origin xyz="0.02 0.02 0 " rpy="${M_PI/2} 0 0" /> 
	</xacro:caster_link>
	
	<wheel fb="front" lr="right" parent="base_link" translateX="0" translateY="0.5" flipY="1"/>
	<wheel fb="front" lr="left" parent="base_link" translateX="0" translateY="-0.5" flipY="1"/>

  
  <!-- Differential drive controller  -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <legacyMode>true</legacyMode>
      <rosDebugLevel>Debug</rosDebugLevel>
      <publishWheelTF>false</publishWheelTF>
      <robotNamespace>/</robotNamespace>
      <publishTf>1</publishTf>
      <publishWheelJointState>false</publishWheelJointState>
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <leftJoint>front_left_wheel_joint</leftJoint>
      <rightJoint>front_right_wheel_joint</rightJoint>
      <wheelSeparation>${2*base_radius}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <broadcastTF>1</broadcastTF>
      <wheelTorque>30</wheelTorque>
      <wheelAcceleration>1.8</wheelAcceleration>
      <commandTopic>cmd_vel</commandTopic>
      <odometryFrame>odom</odometryFrame> 
      <odometryTopic>odom</odometryTopic> 
      <robotBaseFrame>base_link</robotBaseFrame>
    </plugin>
  </gazebo> 

 
</robot>
